quantfoot:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dagster') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dagster_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'football_data') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
